services:
  webapp:
    container_name: one-review-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionStrings__DefaultConnection=Host=db;port=5432;Database=onerevew;Username=postgres;Password=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: one-review-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=onerevew
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d onerevew"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
